name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
env:
  CI: false 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.1.0'
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build project
        run: npm run build
        working-directory: ./frontend
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EKAC_437BC }}'
          channelId: live
          projectId: ekac-437bc
